public class CustomLookup_product {

public String searchByName {get;set;}
public CustomLookup_product(){
/*  Apttus_Config2__ProductAttributeGroupMember__c[] ProdAttributeGroupmemberId = [SELECT Apttus_Config2__AttributeGroupId__r.Id FROM Apttus_Config2__ProductAttributeGroupMember__c WHERE Apttus_Config2__ProductId__r.Id = : ProdId Limit 1];
   if(ProdAttributeGroupmemberId.size() >0){
   system.debug('ProdAttributeGroupId :'+ProdAttributeGroupmemberId[0].Apttus_Config2__AttributeGroupId__c);
   AttFields = [SELECT Apttus_Config2__Field__c,Apttus_Config2__Sequence__c FROM Apttus_Config2__ProductAttribute__c WHERE Apttus_Config2__AttributeGroupId__r.Id = : ProdAttributeGroupmemberId[0].Apttus_Config2__AttributeGroupId__c ORDER BY Apttus_Config2__Sequence__c];
 */
}
}