/**
 * @description A class that handles the static variable for Account update.
 * @author Cloud Sherpas 
 * @date 19.AUG.2013
 *      modification - <Name - Date>
 */
public class SetSendToEmailFlag {
    public static boolean runAfterUpdate = false;
    public static boolean fromTerritory = false;
    public static boolean alreadySync= false;
    public static boolean primaryalreadydelete= false;
    public static boolean byPassTrigger= false;
}